twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/errors.html.twig'
    globals:
        PATH_GRAPHICS: 'images/graphics/'
        IUBENDA_IT: "%iubenda_it%"
        IUBENDA_SITE: "%iubenda_site%"

when@test:
    twig:
        strict_variables: true
